// tailwind.config.js
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
   theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#584400",
        "surface-container-highest": "#dee2ec",
        "surface-container-high": "#e4e8f2",
        surface: "#f8f9ff",
        "on-primary-container": "#fffbff",
        primary: "#bc0007",
        "on-tertiary-container": "#fefcff",
        "surface-dim": "#d6dae4",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#001b3d",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#241a00",
        "surface-variant": "#dee2ec",
        "error-container": "#ffdad6",
        "surface-tint": "#c00008",
        "primary-container": "#e90d11",
        "on-primary-fixed": "#410001",
        "inverse-primary": "#ffb4a9",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "secondary-container": "#ffcb09",
        "on-error": "#ffffff",
        "inverse-surface": "#2c3138",
        "on-tertiary-fixed-variant": "#00468b",
        error: "#ba1a1a",
        "on-surface": "#171c23",
        background: "#f8f9ff",
        "tertiary-fixed-dim": "#a9c7ff",
        "tertiary-fixed": "#d6e3ff",
        "surface-container-low": "#f0f4fd",
        "secondary-fixed-dim": "#f2c000",
        "outline-variant": "#e9bcb6",
        "primary-fixed": "#ffdad5",
        tertiary: "#005bb2",
        "on-surface-variant": "#5e3f3a",
        outline: "#936e69",
        secondary: "#745b00",
        "secondary-fixed": "#ffe08d",
        "tertiary-container": "#2874d2",
        "on-background": "#171c23",
        "on-primary-fixed-variant": "#930004",
        "surface-container": "#eaeef8",
        "inverse-on-surface": "#edf1fb",
        "on-secondary-container": "#6f5700",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#ffb4a9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "2.5rem",
        "space-lg": "1.25rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        gutter: "1rem",
        "margin-tablet": "1.5rem",
        "space-md": "0.75rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        "label-md": ["Space Grotesk"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "label-sm": ["Space Grotesk"],
        "label-lg": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "display-lg-mobile": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "headline-sm": ["Space Grotesk"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};